networks:
  todo_network:
    driver: bridge

services:
  postgres:
    container_name: postgres_todo
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todoapp
    ports:
      - 5432:5432
    networks:
      - todo_network
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/todoapp
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URI=postgresql://postgres:password@postgres_todo:5432/todoapp?sslmode=disable
      - GIN_MODE=release
    ports:
      - 8080:8080
    networks:
      - todo_network
    depends_on:
      - postgres
    entrypoint:
      ["/app/wait-for.sh", "postgres_todo:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
