networks:
  rpl_network:
    driver: bridge
services:
  postgres:
    container_name: postgres_rpl
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - rpl_network
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/rpl_db
  redis:
    container_name: redis_rpl
    image: redis:7.2.4-alpine
    env_file:
      - .env
    ports:
      - 6379:6379
    networks:
      - rpl_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - rpl_network
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/wait-for.sh", "postgres_rpl:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
