networks:
  todo_network:
    driver: bridge

services:
  postgres:
    container_name: postgres_todo
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todoapp
    ports:
      - 5432:5432
    networks:
      - todo_network
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/todoapp
  redis:
    container_name: redis_todo
    image: redis:7.2.4-alpine
    environment:
      - REIDS_PASSWORD=password
      - REDIS_DB=0
    ports:
      - 6379:6379
    networks:
      - todo_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - todo_network
    depends_on:
      - postgres
      - redis
    entrypoint:
      ["/app/wait-for.sh", "postgres_todo:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
