name: go-ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.21.3
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.3
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run tests
      run: make test
